[package]
name = "custom"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token_objects = "0x4"
admin_addr = "0x3c15016877b2ba1a9227f47b1e2284287c500d11b7f7f3c1d09a53282d9dd1a1"
dev_wallet = "0xc336adac7461c219f385095659bb1a8b759d1472d7ad69c9cf495b8770e43d73"
withdraw_wallet = "0xed018ed192b4735c2cda4ef7720ff7784ee5f599be229968ac3c93df739413ab"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
